# Generated by Django 5.2.8 on 2026-02-09 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_app", "0002_alter_contact_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="username",
            new_name="name",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile",
            field=models.CharField(max_length=10),
        ),
    ]
