# Generated by Django 4.2 on 2026-03-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_app",
            "0003_rename_username_contact_name_contact_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="region",
            new_name="subject",
        ),
    ]
